package cz.cvut.fit.culkajac.dp.services.store

global org.switchyard.Exchange exchange;

import cz.cvut.fit.culkajac.dp.dto.FileDTO;
import cz.cvut.fit.culkajac.dp.Constants;

import java.util.Set;
import org.switchyard.Property;
import org.switchyard.Scope;


rule "Add Google Docs route - STORE"
	
    when
        #conditions
        $msg : FileDTO(metadata.extension in ("txt", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "pdf"), metadata.targetService == "") || FileDTO(metadata.targetService == Constants.GoogleDocs.ROUTE_ID)
    then
        #actions

    	((Set)exchange.getContext().getProperty("destinationRoutes", Scope.IN).getValue()).add(Constants.GoogleDocs.ROUTE_ID);
end

rule "Add Google Photos route - STORE"

    when
        #conditions
        $msg : FileDTO(metadata.extension in ("jpeg", "jpg", "tif", "tiff", "bmp", "gif", "png", "tga"), metadata.targetService == "") || FileDTO(metadata.targetService == Constants.Picasa.ROUTE_ID)
    then
    	#actions
    	((Set)exchange.getContext().getProperty("destinationRoutes", Scope.IN).getValue()).add(Constants.Picasa.ROUTE_ID);
end

rule "Add S3 route - STORE"


    when
        #conditions
        $msg : FileDTO(metadata.targetService == "") || FileDTO(metadata.targetService == Constants.AmazonS3.ROUTE_ID)
    then
    	#actions
    	((Set)exchange.getContext().getProperty("destinationRoutes", Scope.IN).getValue()).add(Constants.AmazonS3.ROUTE_ID);
end

rule "Add Dropbox route - STORE"

    when
        #conditions
        $msg : FileDTO(metadata.extension in ("dropbox"), metadata.targetService == "") || FileDTO(metadata.targetService == Constants.Dropbox.ROUTE_ID)
    then
    	#actions
    	((Set)exchange.getContext().getProperty("destinationRoutes", Scope.IN).getValue()).add(Constants.Dropbox.ROUTE_ID);
end