//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 07:35:52 odp. CET 
//


package cz.cvut.fit.culkajac.dp.services.amazons3.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceBucket" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SourceKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestinationBucket" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DestinationKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MetadataDirective" type="{http://s3.amazonaws.com/doc/2006-03-01/}MetadataDirective" minOccurs="0"/>
 *         &lt;element name="Metadata" type="{http://s3.amazonaws.com/doc/2006-03-01/}MetadataEntry" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="AccessControlList" type="{http://s3.amazonaws.com/doc/2006-03-01/}AccessControlList" minOccurs="0"/>
 *         &lt;element name="CopySourceIfModifiedSince" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="CopySourceIfUnmodifiedSince" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="CopySourceIfMatch" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="CopySourceIfNoneMatch" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="StorageClass" type="{http://s3.amazonaws.com/doc/2006-03-01/}StorageClass" minOccurs="0"/>
 *         &lt;element name="AWSAccessKeyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Signature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Credential" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceBucket",
    "sourceKey",
    "destinationBucket",
    "destinationKey",
    "metadataDirective",
    "metadata",
    "accessControlList",
    "copySourceIfModifiedSince",
    "copySourceIfUnmodifiedSince",
    "copySourceIfMatch",
    "copySourceIfNoneMatch",
    "storageClass",
    "awsAccessKeyId",
    "timestamp",
    "signature",
    "credential"
})
@XmlRootElement(name = "CopyObject")
public class CopyObject {

    @XmlElement(name = "SourceBucket", required = true)
    protected String sourceBucket;
    @XmlElement(name = "SourceKey", required = true)
    protected String sourceKey;
    @XmlElement(name = "DestinationBucket", required = true)
    protected String destinationBucket;
    @XmlElement(name = "DestinationKey", required = true)
    protected String destinationKey;
    @XmlElement(name = "MetadataDirective")
    protected MetadataDirective metadataDirective;
    @XmlElement(name = "Metadata")
    protected List<MetadataEntry> metadata;
    @XmlElement(name = "AccessControlList")
    protected AccessControlList accessControlList;
    @XmlElement(name = "CopySourceIfModifiedSince")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar copySourceIfModifiedSince;
    @XmlElement(name = "CopySourceIfUnmodifiedSince")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar copySourceIfUnmodifiedSince;
    @XmlElement(name = "CopySourceIfMatch")
    protected List<String> copySourceIfMatch;
    @XmlElement(name = "CopySourceIfNoneMatch")
    protected List<String> copySourceIfNoneMatch;
    @XmlElement(name = "StorageClass")
    protected StorageClass storageClass;
    @XmlElement(name = "AWSAccessKeyId")
    protected String awsAccessKeyId;
    @XmlElement(name = "Timestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(name = "Signature")
    protected String signature;
    @XmlElement(name = "Credential")
    protected String credential;

    /**
     * Gets the value of the sourceBucket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBucket() {
        return sourceBucket;
    }

    /**
     * Sets the value of the sourceBucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBucket(String value) {
        this.sourceBucket = value;
    }

    /**
     * Gets the value of the sourceKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceKey() {
        return sourceKey;
    }

    /**
     * Sets the value of the sourceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceKey(String value) {
        this.sourceKey = value;
    }

    /**
     * Gets the value of the destinationBucket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationBucket() {
        return destinationBucket;
    }

    /**
     * Sets the value of the destinationBucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationBucket(String value) {
        this.destinationBucket = value;
    }

    /**
     * Gets the value of the destinationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationKey() {
        return destinationKey;
    }

    /**
     * Sets the value of the destinationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationKey(String value) {
        this.destinationKey = value;
    }

    /**
     * Gets the value of the metadataDirective property.
     * 
     * @return
     *     possible object is
     *     {@link MetadataDirective }
     *     
     */
    public MetadataDirective getMetadataDirective() {
        return metadataDirective;
    }

    /**
     * Sets the value of the metadataDirective property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataDirective }
     *     
     */
    public void setMetadataDirective(MetadataDirective value) {
        this.metadataDirective = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataEntry }
     * 
     * 
     */
    public List<MetadataEntry> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<MetadataEntry>();
        }
        return this.metadata;
    }

    /**
     * Gets the value of the accessControlList property.
     * 
     * @return
     *     possible object is
     *     {@link AccessControlList }
     *     
     */
    public AccessControlList getAccessControlList() {
        return accessControlList;
    }

    /**
     * Sets the value of the accessControlList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessControlList }
     *     
     */
    public void setAccessControlList(AccessControlList value) {
        this.accessControlList = value;
    }

    /**
     * Gets the value of the copySourceIfModifiedSince property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCopySourceIfModifiedSince() {
        return copySourceIfModifiedSince;
    }

    /**
     * Sets the value of the copySourceIfModifiedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCopySourceIfModifiedSince(XMLGregorianCalendar value) {
        this.copySourceIfModifiedSince = value;
    }

    /**
     * Gets the value of the copySourceIfUnmodifiedSince property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCopySourceIfUnmodifiedSince() {
        return copySourceIfUnmodifiedSince;
    }

    /**
     * Sets the value of the copySourceIfUnmodifiedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCopySourceIfUnmodifiedSince(XMLGregorianCalendar value) {
        this.copySourceIfUnmodifiedSince = value;
    }

    /**
     * Gets the value of the copySourceIfMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copySourceIfMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopySourceIfMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCopySourceIfMatch() {
        if (copySourceIfMatch == null) {
            copySourceIfMatch = new ArrayList<String>();
        }
        return this.copySourceIfMatch;
    }

    /**
     * Gets the value of the copySourceIfNoneMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copySourceIfNoneMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopySourceIfNoneMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCopySourceIfNoneMatch() {
        if (copySourceIfNoneMatch == null) {
            copySourceIfNoneMatch = new ArrayList<String>();
        }
        return this.copySourceIfNoneMatch;
    }

    /**
     * Gets the value of the storageClass property.
     * 
     * @return
     *     possible object is
     *     {@link StorageClass }
     *     
     */
    public StorageClass getStorageClass() {
        return storageClass;
    }

    /**
     * Sets the value of the storageClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageClass }
     *     
     */
    public void setStorageClass(StorageClass value) {
        this.storageClass = value;
    }

    /**
     * Gets the value of the awsAccessKeyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAWSAccessKeyId() {
        return awsAccessKeyId;
    }

    /**
     * Sets the value of the awsAccessKeyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAWSAccessKeyId(String value) {
        this.awsAccessKeyId = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignature(String value) {
        this.signature = value;
    }

    /**
     * Gets the value of the credential property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredential() {
        return credential;
    }

    /**
     * Sets the value of the credential property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredential(String value) {
        this.credential = value;
    }

}
