//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 07:35:52 odp. CET 
//


package cz.cvut.fit.culkajac.dp.services.amazons3.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Bucket" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GetMetadata" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="GetData" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="InlineData" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ByteRangeStart" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ByteRangeEnd" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="IfModifiedSince" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IfUnmodifiedSince" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IfMatch" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="IfNoneMatch" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="ReturnCompleteObjectOnConditionFailure" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AWSAccessKeyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Signature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Credential" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bucket",
    "key",
    "getMetadata",
    "getData",
    "inlineData",
    "byteRangeStart",
    "byteRangeEnd",
    "ifModifiedSince",
    "ifUnmodifiedSince",
    "ifMatch",
    "ifNoneMatch",
    "returnCompleteObjectOnConditionFailure",
    "awsAccessKeyId",
    "timestamp",
    "signature",
    "credential"
})
@XmlRootElement(name = "GetObjectExtended")
public class GetObjectExtended {

    @XmlElement(name = "Bucket", required = true)
    protected String bucket;
    @XmlElement(name = "Key", required = true)
    protected String key;
    @XmlElement(name = "GetMetadata")
    protected boolean getMetadata;
    @XmlElement(name = "GetData")
    protected boolean getData;
    @XmlElement(name = "InlineData")
    protected boolean inlineData;
    @XmlElement(name = "ByteRangeStart")
    protected Long byteRangeStart;
    @XmlElement(name = "ByteRangeEnd")
    protected Long byteRangeEnd;
    @XmlElement(name = "IfModifiedSince")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ifModifiedSince;
    @XmlElement(name = "IfUnmodifiedSince")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ifUnmodifiedSince;
    @XmlElement(name = "IfMatch")
    protected List<String> ifMatch;
    @XmlElement(name = "IfNoneMatch")
    protected List<String> ifNoneMatch;
    @XmlElement(name = "ReturnCompleteObjectOnConditionFailure")
    protected Boolean returnCompleteObjectOnConditionFailure;
    @XmlElement(name = "AWSAccessKeyId")
    protected String awsAccessKeyId;
    @XmlElement(name = "Timestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(name = "Signature")
    protected String signature;
    @XmlElement(name = "Credential")
    protected String credential;

    /**
     * Gets the value of the bucket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * Sets the value of the bucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBucket(String value) {
        this.bucket = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the getMetadata property.
     * 
     */
    public boolean isGetMetadata() {
        return getMetadata;
    }

    /**
     * Sets the value of the getMetadata property.
     * 
     */
    public void setGetMetadata(boolean value) {
        this.getMetadata = value;
    }

    /**
     * Gets the value of the getData property.
     * 
     */
    public boolean isGetData() {
        return getData;
    }

    /**
     * Sets the value of the getData property.
     * 
     */
    public void setGetData(boolean value) {
        this.getData = value;
    }

    /**
     * Gets the value of the inlineData property.
     * 
     */
    public boolean isInlineData() {
        return inlineData;
    }

    /**
     * Sets the value of the inlineData property.
     * 
     */
    public void setInlineData(boolean value) {
        this.inlineData = value;
    }

    /**
     * Gets the value of the byteRangeStart property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getByteRangeStart() {
        return byteRangeStart;
    }

    /**
     * Sets the value of the byteRangeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setByteRangeStart(Long value) {
        this.byteRangeStart = value;
    }

    /**
     * Gets the value of the byteRangeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getByteRangeEnd() {
        return byteRangeEnd;
    }

    /**
     * Sets the value of the byteRangeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setByteRangeEnd(Long value) {
        this.byteRangeEnd = value;
    }

    /**
     * Gets the value of the ifModifiedSince property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIfModifiedSince() {
        return ifModifiedSince;
    }

    /**
     * Sets the value of the ifModifiedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIfModifiedSince(XMLGregorianCalendar value) {
        this.ifModifiedSince = value;
    }

    /**
     * Gets the value of the ifUnmodifiedSince property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIfUnmodifiedSince() {
        return ifUnmodifiedSince;
    }

    /**
     * Sets the value of the ifUnmodifiedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIfUnmodifiedSince(XMLGregorianCalendar value) {
        this.ifUnmodifiedSince = value;
    }

    /**
     * Gets the value of the ifMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ifMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIfMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIfMatch() {
        if (ifMatch == null) {
            ifMatch = new ArrayList<String>();
        }
        return this.ifMatch;
    }

    /**
     * Gets the value of the ifNoneMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ifNoneMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIfNoneMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIfNoneMatch() {
        if (ifNoneMatch == null) {
            ifNoneMatch = new ArrayList<String>();
        }
        return this.ifNoneMatch;
    }

    /**
     * Gets the value of the returnCompleteObjectOnConditionFailure property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnCompleteObjectOnConditionFailure() {
        return returnCompleteObjectOnConditionFailure;
    }

    /**
     * Sets the value of the returnCompleteObjectOnConditionFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnCompleteObjectOnConditionFailure(Boolean value) {
        this.returnCompleteObjectOnConditionFailure = value;
    }

    /**
     * Gets the value of the awsAccessKeyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAWSAccessKeyId() {
        return awsAccessKeyId;
    }

    /**
     * Sets the value of the awsAccessKeyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAWSAccessKeyId(String value) {
        this.awsAccessKeyId = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignature(String value) {
        this.signature = value;
    }

    /**
     * Gets the value of the credential property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredential() {
        return credential;
    }

    /**
     * Sets the value of the credential property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredential(String value) {
        this.credential = value;
    }

}
