//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.12 at 04:16:44 odp. CET 
//

package cz.cvut.fit.culkajac.dp.services.amazons3.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

import cz.cvut.fit.culkajac.dp.interceptors.Logged;
import cz.cvut.fit.culkajac.dp.services.amazons3.AmazonS3Signable;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Bucket" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GetMetadata" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="GetData" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="InlineData" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AWSAccessKeyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Signature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Credential" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "bucket", "key", "getMetadata", "getData", "inlineData", "awsAccessKeyId", "timestamp",
		"signature", "credential" })
@XmlRootElement(name = "GetObject")
public class GetObject implements AmazonS3Signable {

	@XmlElement(name = "Bucket", required = true)
	protected String bucket;
	@XmlElement(name = "Key", required = true)
	protected String key;
	@XmlElement(name = "GetMetadata")
	protected boolean getMetadata;
	@XmlElement(name = "GetData")
	protected boolean getData;
	@XmlElement(name = "InlineData")
	protected boolean inlineData;
	@XmlElement(name = "AWSAccessKeyId")
	protected String awsAccessKeyId;
	@XmlElement(name = "Timestamp")
	@XmlSchemaType(name = "dateTime")
	protected Date timestamp;
	@XmlElement(name = "Signature")
	protected String signature;
	@XmlElement(name = "Credential")
	protected String credential;

	/**
	 * Gets the value of the bucket property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBucket() {
		return bucket;
	}

	/**
	 * Sets the value of the bucket property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBucket(String value) {
		this.bucket = value;
	}

	/**
	 * Gets the value of the key property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getKey() {
		return key;
	}

	/**
	 * Sets the value of the key property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setKey(String value) {
		this.key = value;
	}

	/**
	 * Gets the value of the getMetadata property.
	 * 
	 */
	public boolean isGetMetadata() {
		return getMetadata;
	}

	/**
	 * Sets the value of the getMetadata property.
	 * 
	 */
	public void setGetMetadata(boolean value) {
		this.getMetadata = value;
	}

	/**
	 * Gets the value of the getData property.
	 * 
	 */
	public boolean isGetData() {
		return getData;
	}

	/**
	 * Sets the value of the getData property.
	 * 
	 */
	public void setGetData(boolean value) {
		this.getData = value;
	}

	/**
	 * Gets the value of the inlineData property.
	 * 
	 */
	public boolean isInlineData() {
		return inlineData;
	}

	/**
	 * Sets the value of the inlineData property.
	 * 
	 */
	public void setInlineData(boolean value) {
		this.inlineData = value;
	}

	/**
	 * Gets the value of the awsAccessKeyId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAWSAccessKeyId() {
		return awsAccessKeyId;
	}

	/**
	 * Sets the value of the awsAccessKeyId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAWSAccessKeyId(String value) {
		this.awsAccessKeyId = value;
	}

	/**
	 * Gets the value of the timestamp property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * Sets the value of the timestamp property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setTimestamp(Date value) {
		this.timestamp = value;
	}

	/**
	 * Gets the value of the signature property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * Sets the value of the signature property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSignature(String value) {
		this.signature = value;
	}

	/**
	 * Gets the value of the credential property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCredential() {
		return credential;
	}

	/**
	 * Sets the value of the credential property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCredential(String value) {
		this.credential = value;
	}

	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this);
	}

}
