//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 07:35:52 odp. CET 
//


package cz.cvut.fit.culkajac.dp.services.amazons3.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListVersionsResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListVersionsResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Metadata" type="{http://s3.amazonaws.com/doc/2006-03-01/}MetadataEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KeyMarker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VersionIdMarker" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NextKeyMarker" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NextVersionIdMarker" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxKeys" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Delimiter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsTruncated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Version" type="{http://s3.amazonaws.com/doc/2006-03-01/}VersionEntry"/>
 *           &lt;element name="DeleteMarker" type="{http://s3.amazonaws.com/doc/2006-03-01/}DeleteMarkerEntry"/>
 *         &lt;/choice>
 *         &lt;element name="CommonPrefixes" type="{http://s3.amazonaws.com/doc/2006-03-01/}PrefixEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListVersionsResult", propOrder = {
    "metadata",
    "name",
    "prefix",
    "keyMarker",
    "versionIdMarker",
    "nextKeyMarker",
    "nextVersionIdMarker",
    "maxKeys",
    "delimiter",
    "isTruncated",
    "versionOrDeleteMarker",
    "commonPrefixes"
})
public class ListVersionsResult {

    @XmlElement(name = "Metadata")
    protected List<MetadataEntry> metadata;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Prefix", required = true)
    protected String prefix;
    @XmlElement(name = "KeyMarker", required = true)
    protected String keyMarker;
    @XmlElement(name = "VersionIdMarker", required = true)
    protected String versionIdMarker;
    @XmlElement(name = "NextKeyMarker")
    protected String nextKeyMarker;
    @XmlElement(name = "NextVersionIdMarker")
    protected String nextVersionIdMarker;
    @XmlElement(name = "MaxKeys")
    protected int maxKeys;
    @XmlElement(name = "Delimiter")
    protected String delimiter;
    @XmlElement(name = "IsTruncated")
    protected boolean isTruncated;
    @XmlElements({
        @XmlElement(name = "Version", type = VersionEntry.class),
        @XmlElement(name = "DeleteMarker", type = DeleteMarkerEntry.class)
    })
    protected List<Object> versionOrDeleteMarker;
    @XmlElement(name = "CommonPrefixes")
    protected List<PrefixEntry> commonPrefixes;

    /**
     * Gets the value of the metadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataEntry }
     * 
     * 
     */
    public List<MetadataEntry> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<MetadataEntry>();
        }
        return this.metadata;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the keyMarker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyMarker() {
        return keyMarker;
    }

    /**
     * Sets the value of the keyMarker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyMarker(String value) {
        this.keyMarker = value;
    }

    /**
     * Gets the value of the versionIdMarker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionIdMarker() {
        return versionIdMarker;
    }

    /**
     * Sets the value of the versionIdMarker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionIdMarker(String value) {
        this.versionIdMarker = value;
    }

    /**
     * Gets the value of the nextKeyMarker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextKeyMarker() {
        return nextKeyMarker;
    }

    /**
     * Sets the value of the nextKeyMarker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextKeyMarker(String value) {
        this.nextKeyMarker = value;
    }

    /**
     * Gets the value of the nextVersionIdMarker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextVersionIdMarker() {
        return nextVersionIdMarker;
    }

    /**
     * Sets the value of the nextVersionIdMarker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextVersionIdMarker(String value) {
        this.nextVersionIdMarker = value;
    }

    /**
     * Gets the value of the maxKeys property.
     * 
     */
    public int getMaxKeys() {
        return maxKeys;
    }

    /**
     * Sets the value of the maxKeys property.
     * 
     */
    public void setMaxKeys(int value) {
        this.maxKeys = value;
    }

    /**
     * Gets the value of the delimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelimiter() {
        return delimiter;
    }

    /**
     * Sets the value of the delimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelimiter(String value) {
        this.delimiter = value;
    }

    /**
     * Gets the value of the isTruncated property.
     * 
     */
    public boolean isIsTruncated() {
        return isTruncated;
    }

    /**
     * Sets the value of the isTruncated property.
     * 
     */
    public void setIsTruncated(boolean value) {
        this.isTruncated = value;
    }

    /**
     * Gets the value of the versionOrDeleteMarker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the versionOrDeleteMarker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVersionOrDeleteMarker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VersionEntry }
     * {@link DeleteMarkerEntry }
     * 
     * 
     */
    public List<Object> getVersionOrDeleteMarker() {
        if (versionOrDeleteMarker == null) {
            versionOrDeleteMarker = new ArrayList<Object>();
        }
        return this.versionOrDeleteMarker;
    }

    /**
     * Gets the value of the commonPrefixes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commonPrefixes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommonPrefixes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrefixEntry }
     * 
     * 
     */
    public List<PrefixEntry> getCommonPrefixes() {
        if (commonPrefixes == null) {
            commonPrefixes = new ArrayList<PrefixEntry>();
        }
        return this.commonPrefixes;
    }

}
