//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 07:35:52 odp. CET 
//


package cz.cvut.fit.culkajac.dp.services.amazons3.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListAllMyBucketsResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListAllMyBucketsResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Owner" type="{http://s3.amazonaws.com/doc/2006-03-01/}CanonicalUser"/>
 *         &lt;element name="Buckets" type="{http://s3.amazonaws.com/doc/2006-03-01/}ListAllMyBucketsList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListAllMyBucketsResult", propOrder = {
    "owner",
    "buckets"
})
public class ListAllMyBucketsResult {

    @XmlElement(name = "Owner", required = true)
    protected CanonicalUser owner;
    @XmlElement(name = "Buckets", required = true)
    protected ListAllMyBucketsList buckets;

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link CanonicalUser }
     *     
     */
    public CanonicalUser getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link CanonicalUser }
     *     
     */
    public void setOwner(CanonicalUser value) {
        this.owner = value;
    }

    /**
     * Gets the value of the buckets property.
     * 
     * @return
     *     possible object is
     *     {@link ListAllMyBucketsList }
     *     
     */
    public ListAllMyBucketsList getBuckets() {
        return buckets;
    }

    /**
     * Sets the value of the buckets property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListAllMyBucketsList }
     *     
     */
    public void setBuckets(ListAllMyBucketsList value) {
        this.buckets = value;
    }

}
