//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 07:35:52 odp. CET 
//


package cz.cvut.fit.culkajac.dp.services.amazons3.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoggingSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoggingSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TargetBucket" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TargetPrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TargetGrants" type="{http://s3.amazonaws.com/doc/2006-03-01/}AccessControlList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoggingSettings", propOrder = {
    "targetBucket",
    "targetPrefix",
    "targetGrants"
})
public class LoggingSettings {

    @XmlElement(name = "TargetBucket", required = true)
    protected String targetBucket;
    @XmlElement(name = "TargetPrefix", required = true)
    protected String targetPrefix;
    @XmlElement(name = "TargetGrants")
    protected AccessControlList targetGrants;

    /**
     * Gets the value of the targetBucket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetBucket() {
        return targetBucket;
    }

    /**
     * Sets the value of the targetBucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetBucket(String value) {
        this.targetBucket = value;
    }

    /**
     * Gets the value of the targetPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetPrefix() {
        return targetPrefix;
    }

    /**
     * Sets the value of the targetPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetPrefix(String value) {
        this.targetPrefix = value;
    }

    /**
     * Gets the value of the targetGrants property.
     * 
     * @return
     *     possible object is
     *     {@link AccessControlList }
     *     
     */
    public AccessControlList getTargetGrants() {
        return targetGrants;
    }

    /**
     * Sets the value of the targetGrants property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessControlList }
     *     
     */
    public void setTargetGrants(AccessControlList value) {
        this.targetGrants = value;
    }

}
