//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 07:35:52 odp. CET 
//


package cz.cvut.fit.culkajac.dp.services.amazons3.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VersioningConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersioningConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://s3.amazonaws.com/doc/2006-03-01/}VersioningStatus" minOccurs="0"/>
 *         &lt;element name="MfaDelete" type="{http://s3.amazonaws.com/doc/2006-03-01/}MfaDeleteStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersioningConfiguration", propOrder = {
    "status",
    "mfaDelete"
})
public class VersioningConfiguration {

    @XmlElement(name = "Status")
    protected VersioningStatus status;
    @XmlElement(name = "MfaDelete")
    protected MfaDeleteStatus mfaDelete;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link VersioningStatus }
     *     
     */
    public VersioningStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersioningStatus }
     *     
     */
    public void setStatus(VersioningStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the mfaDelete property.
     * 
     * @return
     *     possible object is
     *     {@link MfaDeleteStatus }
     *     
     */
    public MfaDeleteStatus getMfaDelete() {
        return mfaDelete;
    }

    /**
     * Sets the value of the mfaDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link MfaDeleteStatus }
     *     
     */
    public void setMfaDelete(MfaDeleteStatus value) {
        this.mfaDelete = value;
    }

}
